name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      ambiente:
        description: "Ambiente destino (solo decorativo por ahora)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
      # branch:
      #   description: "Rama a desplegar"
      #   required: true
      #   default: "develop"



env:
  GCP_SERVICE_NAME: ${{ vars.GCP_SERVICE_NAME }}
  GCP_IMAGE_NAME: ${{ vars.GCP_IMAGE_NAME }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  DEPLOY_ENV: ${{ github.event.inputs.ambiente }}
  GCP_ARTIFACT_REPO: classifier-motheboard



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Autenticación con Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
            credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        #   service_account_key: ${{ secrets.GCP_CREDENTIALS_JSON }}
        #   export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet



      - name: Build and Push Docker image to Artifact Registry
        run: |
          IMAGE_URI=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/${{ env.GCP_IMAGE_NAME }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI


      - name: Deploy to Cloud Run
        run: |
          IMAGE_URI=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/${{ env.GCP_IMAGE_NAME }}
          gcloud run deploy ${{ env.GCP_SERVICE_NAME }} \
            --image $IMAGE_URI \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --memory 1Gi \
            --allow-unauthenticated

      - name: 🔍 Debug variables
        run: |
          echo "🧪 Proyecto (GCP_PROJECT_ID): ${{ secrets.GCP_PROJECT_ID }}"
          echo "🧪 Servicio (GCP_SERVICE_NAME): $GCP_SERVICE_NAME"
          echo "🧪 Imagen (GCP_IMAGE_NAME): $GCP_IMAGE_NAME"
          echo "🧪 Región (GCP_REGION): $GCP_REGION"
          echo "🧪 Ambiente (DEPLOY_ENV): $DEPLOY_ENV"